<?php
/**
 * @file
 * green_renters_workshops.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function green_renters_workshops_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Garden, Garden, renter gardening, Renting, the rented spade, trees',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '005311a3-03ba-428f-9b92-690c84c06edd',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => '1970s, books, Garden, Garden, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0083f210-2ed6-4c35-a276-2b844ba0b4bc',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, Garden, indigenous gardening, native gardening, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '00a78470-e937-49cc-bec4-4dba97f37a7d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container, Garden',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '01266eb2-d8a8-4577-93ca-abb9c2139ab2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'animals, ethical, food, vegan, vegan easy challenge',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '01cc3c84-2102-49d4-9d48-6c32c50dbd46',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Environment, film, food, GM, News, real food',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '01fdf4e8-604b-4ebb-83f2-af63a8a77071',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, Garden, onions, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '020c4fb2-2ed4-4667-859f-a1e43e80fe3a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'efficiency, electricity, How to save energy, power, saving, standby, tricklestar, Utilities',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '02b2ea38-bda7-41a9-b8b4-ba53700b62f9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, Garden, Garden, pots, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '03eb6c1b-db21-48a9-957f-80426dd96b63',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, Events, Garden, Garden, pot plants, weekly container gardening spotlight',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '04415dd3-6ccc-4443-afc7-429b1776fde9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container, decorating, Garden, product',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '05a54ddd-64bc-453c-8e90-08766e2a78dc',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, gardening, guerrilla, Kitchen, pickling, preserving',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '06a711ed-d722-46b1-8af5-e70c435204be',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Body & Home',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '06c8ca97-d592-4471-8f9c-593e6f763404',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'fire, fire sfaety, Kitchen, Lounge room, safety',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '076136ef-0eec-4f57-a5e8-d2104c8c8c3c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Australia, carbon footprint, diy, Environment, ethical, Events, food, gardening, green renters, Transport, vegan easy challenge',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '07a85624-1ade-4b60-ac29-f63e3eac5347',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, gardening, guerilla, opinion',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '07aa04de-5ba8-47ae-805f-c03127c072d7',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'vegan, vegan easy challenge',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '08354b93-c1f4-446d-a72a-7baf0c6ceaa2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, Garden, self planting, small space gardening, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0852397f-b3f8-4373-b9ef-2948a6cac0c4',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cardboard box, diy, Kitchen, solar oven',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '08df616c-52e1-4c91-bdf4-ad02a308e050',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'competition, event, film, News, Renting, speed renting',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0908fc74-391f-403f-bd97-1d7d7ad7a2a8',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'awards, green media, Green Wash, News',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '094fd6c8-de3b-4c06-80f0-e35e952dc6b6',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container garden, Garden, gardening',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '096a4d11-2ca4-4a49-8320-e7ff89edb78d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'slow living',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0a9c1721-7216-4769-bc4c-53cb72bdb31a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, Garden, gardening, grass roots, magazine, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0b8bb531-d90b-4824-9c1f-c9231fbbf9ce',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bonsai, Garden, Garden, herbs, the rented spade, thyme',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0c4b8e0d-b3e2-4d40-8b0d-f5dc2da6adac',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container, Garden, gardening, plants.toolbox, recycle, ruse',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0c67151d-ad9c-4a0b-bc99-623937c777e5',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Cheap & Healthy recipes, cooking, healthy, Kitchen, muesli, organic, recipes, snacks, waste reduction',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0cab7cdb-e49c-491b-aaa0-bde694f7393c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, Zucchini',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0d95936e-dd7d-461e-b943-f1d7fa2affa3',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, poster, print',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0d989899-f845-4e58-a219-9aaef5409405',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, boiler, diy, efficiency, energy, How to save energy, insulation, keep warm, Kitchen, lagging, Laundry, pipes, save energy, water heater',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0de78fa3-2626-4d84-92a3-9e758e7fdd53',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, Garden, Garden, gardening in small spaces, go green expo, Products, special offer, yum eyard',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0e814d97-fdd7-4820-a814-433cf33be67c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Earth Hour, event, green renters, News, vote, wwf',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0ee68ecc-8d86-4ad2-aefd-2bf15c4ee4e2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cake, cooking, Garden, Kitchen, lemons, recipe, vegan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0f124f22-2486-4d0d-ad9d-ddab147cf3e4',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Cheap & Healthy recipes, cooking, Garden, Kitchen, pickled, preserves, recipe, Reducing food waste, Zucchini',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '10193f4d-c051-4b67-aa67-3f81ab7d7b79',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'diy, recycle, recycling, Reuse, waste reduction',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1117dc18-f398-4380-9fc3-f9290278da30',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, workshop',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '119fd11e-2fb0-48dd-bd42-19df42202818',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, Garden, olympics, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '11b2a999-2084-483e-9a1e-53d6549ffd68',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, Garden, Garden, the rented spade, tyres',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1267bfcd-3215-4357-9d07-00791eace003',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cooking, Environment, ethical, food, Garden, Kitchen, recipes, Reuse, review, seasonal vegetables, vegetables, waste reduction, ways to reduce waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '12cc53bc-d835-4841-9086-b0e8ab68c366',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, diy, Garden, Garden, Gardening in small spaces, pot plants, recycle, recycling, Reuse, weekly container gardening spotlight',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '12cf0737-76b4-4311-9575-a9961d64d8a2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'campaign, Community, Merchandise, merchandise, rental sweet rental',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '15a0d8f8-235b-4a4f-b09c-2ae7f6c976d2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'conference, green institute, green new deal, News',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '15e604d8-a88d-4ce3-97c9-ed3b65ceb769',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'advice, Green, greenopolis, Kitchen, tips, web site',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '161a4abe-0eb1-4f19-8de8-29ce0b826df0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'celebrations, Christmas, Community, festive, gits, Lounge room, presents, wrapping',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '16a22837-0520-4640-b585-12818a2e4936',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container garden, Garden, Garden, gardening, greensmart, herbs, vegetables, wicking',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '16fc1f72-d33e-42e6-8466-eb0bcaea686c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Christmas, consume less, decorating, diy, free, Garden, Garden, gardening, recycle, recycling, Reuse',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '17de0c27-8d0d-4d83-b6eb-c4e2788c3a27',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, Garden, Garden, the rented spade, trucks',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1877c5af-fcff-4d64-ba8d-35089636c31b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'coffee, dregs, Garden, Kitchen, Reuse, tea',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '18ccb9f6-9e05-44f5-bbe5-5e6a21af4908',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, competition, diy, event, expo, giveaway, rennovation',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '18e24bfd-7d81-4011-a3d5-ede8c5acf586',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'News, poverty, rental. VCOSS, social services',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '193bf471-ab71-45ed-9e8f-e15ab712ab40',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, community, green plumbers, Kitchen, Laundry, plumbing, Utilities',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '19b05327-b3fe-40b6-81f6-273e665980d5',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, community gardens, Garden, Garden, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1aaaf708-ead6-441e-9701-e5761f266bbe',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'article, green renters, help, magazine, News, News',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1bef39c5-5e57-416f-8fb0-f05d705442c4',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Australia, bundanoon, eco town, new south wales, News, Utilities, water',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1ccda15c-de74-4523-bb03-16168c4c23e8',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, gardening, geurilla, planning, seasons',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1cf6e4e5-4989-41ce-9d19-e6a2c17c0c10',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'back yard, container gardening, Garden, Garden, pot plants, recycled pots',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1ebab10e-4879-4d57-865d-ba3c3d6942a0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'advice, Bathroom, Bedroom, winter',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1f7a9e31-fdb2-4c42-93a5-ad0613b5037a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, government, mental health, policy, Renting',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '20c12608-840c-418d-b097-4cb31bda8245',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'carbon footprint, cooking, diet, ethical, food, Kitchen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2151bd1c-10e3-40e2-b9f1-d86f5dd23356',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'carbon footprint, efficiency, electricity, energy, fridge, green your fridge, How to save energy, Kitchen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2221ea36-881d-403b-a1a2-d121019e8ff0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'business, charity, cooking, ethical living, food, frugal living, sustainable living, vegan, vegetarian',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '228acae5-44a2-4f4c-b305-b69369f15638',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bicycles, bike riders, cycling, Transport',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '22a284bd-1c1b-4bc8-bef8-5c4af25e10a8',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, cleanout, Spare room, spring, store',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2394a769-81b2-4a5f-93d6-c1e9aa2958c8',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'City of Yarra 2013, Community, community development, get involved, project',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '24032899-42eb-4748-ad1e-39f4a1001be9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'average, Bathroom, Bedroom, bills, cost, efficiency, energy, Kitchen, Laundry',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2481526f-ea36-4279-849a-253797fca422',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Bedroom, consume less, craft, diy, Environment, ethical, green renting, Kitchen, Laundry, recycle, recycling, Reuse, Spare room, waste reduction, ways to reduce waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '24835a04-21f5-4083-a68c-2cc93ef71d82',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, consume less, consumption, free, frugal living, gauri, Melbourne, spend, waste reduction, ways to reduce waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '24baa513-1b5d-466d-81e4-2f76989da938',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'csiro, household impact, lifestyle, News, Spare room, survey',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '24ce306b-5d39-4b86-ad8a-c97940623778',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Music, Rap, Video',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '251b4800-57be-4d38-8753-371a9cf844d2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cooking, iga, Kitchen, moreland, recipes, recycling, vegan, waste reduction, week without waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2582c648-af17-4937-b1d2-d356abeba6d8',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, Garden, halloween, pumpkins, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '25bc7cee-bce2-456d-a323-43d4044055a4',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'animals, Bedroom, home, law, legal, Lounge room, pets, regulations, rights, Spare room',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '25cdd70b-57bd-4022-b446-6e9e32fd2e7a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'edible, Garden, Garden, gifts, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2626a482-5512-41ca-b9da-5f1121d698a3',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, cooling, door snake, Draught Proofing, draught proofing, Energy saving, energy saving, heating, How to save energy, How to save energy, Spare room, Wholesale',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '27dc4c64-9524-4f04-9655-58ae6638c442',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'dishes, dishwashing liquid, diy, green kitchen, homemade, Kitchen, washing up',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '280c7071-7c4d-4db5-a64e-035d2e2572a6',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cooking, food waste, iga, Kitchen, moreland, News, recycling, Spare room, waste reduction, ways to reduce waste, week without waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '28389077-3c0e-41ac-8811-b8e229c95b71',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bottles, News, recycling, Utilities, waste disposal, ways to reduce waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '28990d5d-d3ee-4c38-bce4-5cd484175647',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'book, competition, craft, giveaway',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '29012824-ac58-42b1-8e53-d0102ee73e43',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Kitchen, Laundry, recycling, storage',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '29389ed1-087e-40b3-b8e3-7bbfeea7ffed',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, SGA, Sustainable Gardeners Alliance',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2a35c195-3448-47c7-a843-9fa58973f7a9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'review, television',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2baa9981-0dc7-4a3a-84f1-44fb26d03075',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, gas, heating, rental, safety, Spare room, winter',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2d3cc87c-f558-444d-bd84-b115c1bd7048',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, gardening, geurilla, tomato',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2d3ced80-2bd2-4efd-ab8d-15092238382f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cooking, eggs, food waste, Kitchen, moreland, recipes, waste reduction, week without waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2d70c8f4-1867-423d-8ae3-c57472888ae0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bird proofing, Garden, gardening, netting, proofing, rabbit proofing',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2e369c30-f2d9-41f3-83df-394ba911207b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'advice, australian federal government, Bathroom, Bedroom, insulation rebate, just change, Kitchen, Laundry, News, Spare room, tips, Utilities, winter',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2e6321ca-d68f-4642-ba00-70a6da184126',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'energy reduction, green cleaning, Laundry, Laundry, reduce packaging, washing, water',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3059ddf6-7f0b-4bb0-a817-85bc9a29b426',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Bedroom, energy, food, Garden, keep warm, Kitchen, Laundry, recycling, Renting, share housing, Spare room, speed renting, waste reduction, water',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '30679f79-bc80-4946-9acd-13e11a8f7e70',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bike',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '30876ec5-2b82-40d7-9ead-302b5773f6d0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'food, Kitchen, recipes, vegan, vegan easy challenge',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '30c4235b-7983-4ba9-85c8-4f3a43c558f2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, event, Garden, gardening, homegarden',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '315a9eba-7d98-4257-b07c-141783c19420',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Green',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '33037ad7-a977-4012-9dca-9041010b8b28',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'article, Australia, green party, green renters, greens, magazine, News',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '332ccf4f-52e3-49fb-b098-054f73a46e1b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'community, event, market, stall',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '33ad3038-035b-484b-9b96-6db58ba89829',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Autopot, Garden, Garden, Garden, Water saving, water saving, watering',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '33fc8f5a-9036-4c91-bf2a-ae3028e4de9a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'resources',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '34f81f51-0981-44e6-a4b8-84d213925f5b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'holiday, plans',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '35328f57-c411-4d3d-9d25-86e3671845be',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bush property, green renters, News, panton hill',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '359e43c0-f3d7-4a3d-983d-1f781111ce6d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Cheap & Healthy recipes, cooking, Kitchen, recipes, vegan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '36c9af33-eb08-4fd9-848f-0ccf71913a30',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container garden, container gardening, Garden, Garden, pot plants, seasonal vegetables, vegetables, weekly container gardening spotlight',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '379b6d4e-5033-45cb-b051-d1a0f5cac618',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Batch, Cheap & Healthy recipes, cooking, food, food waste, Kitchen, recipe',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '37fc7226-8481-4f68-a78c-ea5addb74213',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Christmas, Community, food, presents',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '381063fc-dc80-49e9-88aa-2c9c0fea53c9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, diy, Garden, Garden, gardening, Green, recycle, recycling, Reuse, weekly container gardening spotlight',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '38b21e84-39dc-47ba-8e89-f11e4ad87818',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'balcony gardening, container gardens, Garden, Garden, gardening',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '390169ed-362c-4466-ad17-c95d1a154409',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'carbon footprint, eco, efficient energy use, electricity, ethical, Events, Forum, freeganism, Green, News, workshops',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '39159c3e-1cd3-4b0d-9995-00567541ef6e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'green renters, help, kookaburra awards, ourcommunity',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3944dd66-2e27-429c-bc50-4d866569555a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cleaning, Cleaning products, garden safe, Laundry, washing powder',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '396bcf2c-9e6c-44f7-b821-e26cf0aa0598',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'beer, book, christopher mar o brien, fermenting revolution, Kitchen, review',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '39e6d9d5-15fd-44b7-be07-3930e843d1de',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'beans, Kitchen, recipe',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3a239da8-11eb-4f3d-b475-6342488c2699',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'academic, Community, community development, Events, talks, thriving neighbourhoods',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3ac0c0de-fa7f-449c-9c53-44f716b52e8c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Mobile, News, Phones, solar, Utilities',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3b13a203-283b-46ba-9495-a31adbb310cd',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Cheap & Healthy recipes, fruit, Kitchen, pear, recipe, seasonal produce, winter',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3b1a8cc4-741c-4354-bdbe-1b817268982d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'housing affordability',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3b200542-3b0d-4d2a-9318-99d15ef9bf20',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bike, cold wintery, gloves, News',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3d567fc1-9731-4a8e-ba73-cb20a82fe292',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'animals, Bathroom, conservation, consumers, ethical buying, recycling',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3eacc392-0eee-4047-9684-b668d9628aa0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'carbon footprint, electricity, event, frugal living, sydney',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3ef8a088-8fe5-48ab-aaec-33b1cadcbefc',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'award, Community, Earth Hour, Education, green renters, wwf',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3f9cb2aa-eaf9-4b57-850c-cc12df33c533',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Bedroom, condition, damp, health, Kitchen, Laundry, mould, property, Spare room',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4091f84c-8146-4de7-b23f-dbff4e702407',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => '30dayeasyveganchallenge, vegan, vegan easy challenge',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4144a9ed-170b-40d5-90b5-3f8a24c3dc7f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, london, travel, uk, urban forest, urban regeneration',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4196ff52-ecf4-4ed0-bc75-e8a51f0d2996',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'animals, bird feeder, birds, diy, Garden, pets',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '41c0e0e3-23f4-462b-95aa-1c75da96ceba',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cooking, diy, fruit, jam, jam making, Kitchen, recipes',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '422322ae-846d-40e2-9365-9931eb7e6d54',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Bathroom, Bedroom, eco home, electricity, furniture, green pages, heating, homegarden, Laundry, magazine, Spare room',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '425fe98d-8741-41a5-b09c-0d4aa4d46ddc',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cleaning, green cleaning, Kitchen, Reuse',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '428f9b03-866f-49b4-aea7-8cd3bb802065',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'community composting, composting, Garden, Melbourne, waste reduction',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '42bbe49c-668c-4ada-a2f3-4ab95e6c6dad',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bunting, Garden, Kitchen, old clothes, project, recyling, t-shirt bunting, upcycling',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '43020d43-01d1-4e66-8507-ff54615d133a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'get involved, volunteer, volunteering',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4327c711-9e65-4874-ad59-6fca5d0d8404',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Gardening',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '432c963e-0d1a-4024-9a29-4dae113e4853',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, craft, diy, electricity, recycling, Reuse, sewing, Spare room, tutorial, waste reduction',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '43a75ed6-fd89-4b95-8788-2c0a44e56c33',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container, funny, Garden, humour, recycled, Spare room, storage, the crate man',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '43aef0d8-b5b3-4e2d-b0ee-ef81d49a70dc',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, dual flush, News, regate, saving, toilet, Utilities, water',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4506c5d2-aeb9-422d-9c4e-d22f74943df5',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, Garden, recycled gardening, weekly container gardening spotlight',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '454aed8b-bed0-4d35-aa5d-6e09130a0622',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'about, community',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '45b09b43-814c-4b4a-8adc-ed0c37fb10b6',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'city of Melbourne, computerbank, ewaste, toilet paper, Waste, zoos victoria',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '460f0c8f-32a6-4906-9cd0-15ad1e67af4f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => '',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '466e5061-a968-4ee1-b27b-fe616a3b918b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, Garden, the rented spade, Zucchini',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '470a527a-d195-4cc8-ab4c-dc48d94e4b0d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Australia, Bathroom, Bedroom, green power, Kitchen, Laundry, Spare room, Utilities',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '47cd09dd-fe44-4ed5-9e61-344abd0e31cc',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'joy fm, News, radio, regular, show',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '47fc0953-1649-460a-a65c-eb5911203580',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'festive, Garden, Garden, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '491ae52b-e2a3-45a2-a766-f6f990b4a361',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cooking, food, Kitchen, Kitchen, waste reduction, ways to reduce waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '49402b0c-b328-4792-9a16-64294edd5f8d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'celebrations, Cheap & Healthy recipes, cooking, Easter, food, holiday, Kitchen, recipe',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4983941d-f9e5-4e9c-8bdb-f6b4e990f16f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, norfolk, norwich, travel, uk',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4a626caa-8ddc-40b5-83d2-7369d81dbbf9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'communal eating, Community, community building, dinner, Eatwithme, food, Kitchen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4b198e86-51ab-4481-a92f-f87a7af834e5',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'conference, downloads, presentations, Utilities',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4b6116d2-9645-4de9-a5c2-41e36786d139',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'frugal living, waste reduction, ways to reduce waste. one dollar a day',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4b9ebf57-168f-4b29-a08f-1bed15ff5c72',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cost of food',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4c7b8974-596d-481a-8e9a-02047a321185',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Cheap & Healthy recipes, container gardening, Environment, food, free, frugal living, Garden, Garden, gardening, renter gardening, seasonal vegetables, vegetables, winter vegetables',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4cf14a67-25f3-401a-816c-6ca0a891e092',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, hammy goonan, save energy, shower saver, showers, Utilities, water, water saving',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4d02ec14-e9de-4218-9d0d-1a387bc2eb44',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'eco, Green, marriage, recycle, wedding',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4d869747-749f-4d45-b47e-fbe8acef61ac',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'consume less, food, food waste, Kitchen, reduce food waste, Reducing food waste, save money, Waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4dbca1f3-e119-4988-825f-0b4bd32c60ae',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, Garden, get involved, seed bombs, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4dcfdb79-7b75-4468-b246-07e58a881202',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'food, Kitchen, real food, shopping, supermarket',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4dd365ae-483d-4848-93d8-96cb3548c287',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, Community, dating, family, friends, life, Lounge room, relationships',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4e1ca7b3-8c1a-4b60-8a51-2bd98f532c46',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'articles, luddite, News, Spare room, technology, Utilities, voluntary simplicity',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4e90cc6c-bf3d-4bc9-9b44-ceeb3e767d87',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4ec01918-5ce7-4d17-b7a5-182acf7b8577',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'event, News, waste reduction, ways to reduce waste, workshop',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4f2f4e5f-3891-44cc-81e4-8233d811829f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, gardening, weekly container gardening spotlight, Worm Farm',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4f525d3b-2169-400f-95f4-9bbccd7acfe0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'electricity, energy reduction, Energy Waste, Utilities',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4fc44ba8-5d9b-49e9-8675-aff3c3779e09',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, Garden, Garden, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '500d5eee-6871-4a75-8460-d7f07b43b56f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, gardening, News, Sustainable Gardeners Alliance, sustainibility',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '50210be4-bd30-475d-ab85-c18b0312ff15',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Bathroom, diy toilet cleaner, manure, toilet, water, world toilet day',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '50b2ec6e-fcb5-4e08-94d2-a4108930b92f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'a sea change, competition, environmental film festival, film, News',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '50f2a57d-79b3-4249-ac14-3343b01f7e25',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'baby birds, bird boxes, birds, blue birds, earth day, Garden, nature, nesting, nesting boxes',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '50f4c5f9-49c3-4858-b2ee-8fbba803583a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Environment, green gorilla, kids, resources, television',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '51d36c09-ae21-4bd3-ab14-6b02bd92eea7',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'campaign, Community, fast food, food, Kitchen, waste reduction, ways to reduce waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '531986f9-e7bd-471d-a47f-3013d7ae2c08',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'CAG, Climate action group, Community',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5319bb86-f60c-4d1c-b2e4-9ec397647c0e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Art, Garden, Garden, heide, the rented spade, winter',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '53b5d3b4-0553-4968-aa4f-78f8fa9ce95a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, cleaning, green cleaning, Kitchen, natural cleaning, oranges',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '53f1d931-2484-4957-b0f2-b7f3a6fcaabd',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'advice, Bathroom, Bedroom, Garden, guide, Kitchen, Laundry, News, no impact man, Spare room, tips, Transport, Utilities',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '54441782-de61-4625-9d21-aabe8ac5141a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'advice, Christmas, ethical, family, holidays, Kitchen, new years, Spare room, tips',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '54c70441-f963-4c2d-843f-75da71732ac2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Australia, container gardening, Events, Garden, Garden, gardening, Green, pot plants, seasonal vegetables, tutorial',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '54c70ea4-4e9d-4f17-8c5d-c793add201c7',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'compost, dirt, Garden, gardening, guerrilla',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '55b0a47c-501f-4b47-acd8-223ffb1ca271',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'apricot, Community, jam, Kitchen, recipe',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '560b8321-2633-494d-a49e-594e8eae2629',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'comic, Community, gift, Lounge room, present, recycled, repurposed, Upcycled gifts, upcycling, wallet, Wholesale',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '56766df4-4178-4596-8c69-f5a2d36c8628',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container garden, Garden, Garden, renter gardening, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '577759ea-bce5-40e2-b07f-89ad6c723f74',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'apps, Garden, Garden, Mobile, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '57909615-67e4-4356-b09d-69ce96650847',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => '30 day vegan challenge, carbon footprint, cooking, Environment, Kitchen, News, recipes, vegan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5807dfa4-5c13-4dfd-88f0-ae64b183822a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Merchandise, Upcycled gifts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '583b07a3-e02b-41bd-a683-1e3c08f2e227',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'agm, Community, governance, News',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '586a1a2e-3e93-4049-81b0-8d62397f281c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, cooling, door snake, Draught Proofing, draught proofing, Energy saving, energy saving, heating, How to save energy, Wholesale',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '587a6554-27b2-4e1a-8b3e-b9016f92f617',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Lifestyle',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '58ada19f-71fe-4b2b-8638-65a034896cbe',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, Garden, gardening, gardens, pot plants, propogating plants, Renting, succulents, weekly container gardening spotlight',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '598c9b15-9ba7-4b9a-a6cc-2f087fa0d845',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Cheap & Healthy recipes, cookbook challenge, cooking, Garden, Kitchen, leftovers, recipes, reduce food waste, waste reduction',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '59c6c00e-8d80-429b-b1a7-1373177002d9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'ethical labelling, Kitchen, News, palm oil, vegetable oil',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '59ea9e6b-d897-45f5-8e4a-37f7bfdc8e17',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'alternative education, Community, critical mass, lincolnshire, skills sharing, travel inspirations, uk',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5a6fc3c2-041c-41ec-86a0-36c82288cf7a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'event, festival, green earth',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5ab19698-28ee-4422-8ead-9d5024b0db7b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, craft, dog, Garden, pet ownership, tutorial',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5c2f4725-d541-4dec-b141-f03f9f3e659a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'boroondara, business, carrotmob, Community',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5c91f20b-6885-4c6b-864f-9fe4d20e892c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'solar, solar power, solar products, Utilities',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5cd6165f-fbf7-4984-9f04-300373b22399',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Garden, Kitchen, recycle, Reuse, solar, Utilities, water',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5cfc3d9f-736a-441d-9d7f-eb74fd4359bb',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'appartments, city of port phillip, Community, Melbourne, programs, st kilda',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5d2e7168-bf68-49b8-8522-7457cd0cad53',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Christmas, gift, upcycled, Upcycled gifts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5d51397a-50dc-4a13-a4d9-97a93755e1fa',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Bedroom, energy, hot weather, keeping cool, Kitchen, save energy, Spare room, summer',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5d618c08-e831-4c2b-86ad-b6626c1e68a8',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Bedroom, consume less, craft, diy, Garden, Kitchen, Laundry, recycle, repurpose, Reuse, upcycling',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5d8ace57-5d4f-499e-9871-784cae0ba1ff',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'car hire, cars, Community, inner city, Transport',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5f368497-f663-4af4-b6b1-09657834cf3f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, community, Green, green mapping, mapping, maps, resources',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5fde0a24-62b0-4b5a-8c4e-893e4555f4e2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bicycles, carbon footprint, cooking, cycling, diy, food, frugal living, recycle, Reuse, seasonal vegetables, tutorial, waste reduction, ways to reduce waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6050213d-a9d3-4794-8076-c0f59b717e0c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Cheap & Healthy recipes, cooking, Garden, jam, Kitchen, pears, Reducing food waste, seasonal produce',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '60f892b8-897b-47f8-a6e6-eb9fc98d0da2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bokashi, compost, food waste, Garden, gardening, Kitchen, Reducing food waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '611955b4-85c3-4243-a5cf-9dad9a7c35d2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'clean, donate, ewaste, mobiles, recycle, repurpose, Reuse, Spare room, television, tv, Waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6295906e-7f55-42f5-b002-48b3d6b653f2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'environmental friendly, GM, Kitchen, real food',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '62fed0e7-7d1a-41e8-85df-25157cc0f2c9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, consume less, energy, energy saving, food, How to save energy, How to save water, Kitchen, Lounge room, money saving, Spare room, transport, water',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '631d942e-a933-4a5d-a26b-e173cd50e1ea',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'enviroball, washing ball',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '637b8b19-b6e9-46d3-9e9b-f4585325330b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'aana, advertising, Environment, News, sustainibility',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6430f6d8-b325-4095-9448-819451fd58f0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'film, Melbourne, no impact man, screening',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '64443168-9872-49d3-841c-fc19a0848cd8',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'beer, Garden, Garden, the rented spade, western australia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '647a6d33-44e4-44a6-9fc0-74c0214af8b7',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, diy, Events, Garden, Garden, pot plants, tutorial, weekly container gardening spotlight',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '64c7c141-42c2-45dc-8a21-94f7c47322c0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cooking, Kitchen, seasonal vegetables, vegan, vegan easy challenge, waste reduction, ways to reduce waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '65f14230-6ece-4532-a56b-2ba06d7baa36',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'articles, contribute, green renters, News, review',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '661d4d24-7479-4372-afaa-449ffbfd9cd2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cooking, keeping cool, Kitchen, recipe, things we like',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6657bb24-b0a6-49d3-8703-5a6321cf9ec7',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Home Sustainability',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6816ede1-0326-4212-b116-d5619e58eaa9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bicycle, moving house, Transport',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '68d5afb2-d811-4236-9c48-450edc14ab7d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, community development, get involved, item, lets, resource, sharehood, skills, trading',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6933ec49-807d-49b5-b787-245d481e41ce',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, Garden, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '694579d6-2e4e-4656-8d3b-63b35c05f3ce',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'buy nothing christmas, Christmas, consume less, gift giving',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '69696956-1878-486b-88c6-0e425f75afd2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'food, Garden, gardening, Green, green renters, recipe, sprouts, tutorial, workshop',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '696bc023-09b6-4f6f-ad75-4d5127b42fbb',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'blood sweat',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '697b28be-4ed8-4e0b-a740-4df450df2529',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'craft, diy, eggs, gocco, hankies, make your own bags, moreland, napkins, News, recycling, waste reduction, ways to reduce waste, week without waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6a904534-e7fb-47a6-b9ca-b4d82706094e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, fun, Maribyrnong, Postcards, Renting',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6ad4a335-6034-492b-be2d-9e82e1e32f35',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'electricity, energy saving, How to save energy, power svaing, Spare room, standby',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6b1b983b-6150-49f6-82a9-1a9b223b2361',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'electricity, energy, energy efficient, free, light bulbs, low carbon, Utilities',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6b1d0aae-5eba-41ff-b73e-9b85a34f3935',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, ethical buying, Kitchen, Laundry, News, shopping, supermarket, supermarket tour',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6bdf6d44-54d4-45e0-b48d-097a2c617f5f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, gardening, geurilla',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6c5acfa5-69da-465a-845b-ef038596d18b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bikes, brompton, foldable, folding, storage, Transport, transport, travel',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6c80a6f2-b36e-4826-9368-bab4b55fe4bb',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Cheap & Healthy recipes, food waste, Kitchen, lemons, real food',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6ccdd0e1-54ca-46fd-9cd4-0cb10e4317cf',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'books, recycling, sewing',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6d968997-e7b6-4ca3-a5f7-2f1216d3399d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'documentary, dumpster diving, food, free, freegans, Kitchen, Video',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6df304dc-e0ae-4882-bbe3-f7f3224c12df',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cooking, Garden, Kitchen, recipes, seasonal vegetables, vegetables, winter vegetables',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6e03ebd3-ac31-4f78-9b8b-b177f63ccfab',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'beer, diy, solar, Utilities, water',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6e0e3355-d334-420d-acc4-cd1d49b74f85',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'craft, diy, ethical, frugal living, pot plants, recycle, recycling, Reuse, waste reduction, ways to reduce waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6e3099cf-714d-4011-992b-c8a181097525',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Kitchen, Laundry',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6eaa258a-edda-46d6-9f54-f6427a67c1ec',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, Garden, gardening, grey water, water, water saving',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6fc40e30-1f1c-4b0d-afed-0e867abe2d88',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Australia, diy, ethical, fashion, funny, recycle',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7064690c-0b17-4b46-adf8-4fe8ac34be3e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'dummies guide, green it, hp, Spare room',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '709b647e-13ed-44dd-aab8-aa0d1c4738c4',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Kitchen, Laundry, save energy, saving, smartsaver, Utilities, vegas, water, water flow restrictor, water saving',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '70ff224f-8a6e-403e-bc56-1d586d5d2548',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'craft, design, Kitchen, teapots, waste reduction',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7114178a-dfcd-41f0-b6ed-8c77e83007d4',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Art, Brunswick, Environment, Events, sustainability',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '717d442f-e491-44d0-aaa2-a9e9565ee591',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Art, Community, Garden',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '719082a2-bf4a-41d7-a057-044bcbffc4d8',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Events, green renters, News, workshops',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '71dce42f-8977-4531-a1be-dd3f00f91aa3',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, department of primary industries, electricity, government, smart meters, Utilities, Victoria',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '730c6063-38d3-4827-bb33-42e56cb0a43a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cohousing, communal living, Community, home sweet home, housing, share housing',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '73b4d2b7-ed7f-4f5d-a7d9-dba731f4c1e1',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'recycling, Reuse, Waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7547604d-895f-45bf-a7ee-d5c90054322f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'agm, business, Community, membership',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7548ac32-e288-43db-b55e-dc1fd0db25d7',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'eat by date, food, Kitchen, sell by date, Waste, waste reduction',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '75d19355-3ea0-4060-b3ce-d10fd966c882',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'celebration, Community, event, fundraiser, magic, Music, party, puppets, spring, warm, winter',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '765e3935-0f98-4217-a0cf-eafcb0494b39',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'landlords, News, sustainability awards, yarra',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '768007ca-1a0c-4d8a-95c2-84554d9b51c4',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bicycle, bicycles, bike, council, lights, moreland',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '77c4e46a-97fb-492a-a7e4-8274b2f85f03',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'presents, Spare room, wrap, wrapping',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '78455a20-7b15-4f6d-944d-ac6a28d1de61',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'beetroot, Cheap & Healthy recipes, chutney, cook, cooking, Garden, Kitchen, preserve, Reducing food waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '78e3c6f7-565b-4b4c-a43f-5149c3b3cf38',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Bedroom, Environment, Green, housing, Kitchen, Laundry, rental, Renting',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '79371393-d0f2-4062-a78a-fa5332a7b1e0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'carbon footprint, Google, News',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '79537bba-0a94-49ff-b55b-b3b35c0c0300',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Australia, container gardening, Garden, gardening, green renters, Melbourne, pot plants',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '79f1f00f-871e-4ddc-9ed0-e4c753f07f6d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'asterix, Community, gift, Lounge room, present, recycled, repurposed, Upcycled gifts, wallet, Wholesale',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7a70e574-3431-4a52-961b-4e1291eab268',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Bedroom, Garden, Kitchen, Laundry, Utilities',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7a76025b-8918-4274-b438-8ae4e9fd5cb1',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cooking, diy, food, Garden, Kitchen, recipe, solar, tutorial',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7aa87d07-3c7b-4e60-a735-8ecb62b92e18',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'biodegradable, cloth bags, Community, Environment, plastic bags, recycling, ways to reduce waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7ab526a7-bb64-4453-bbf6-15731252727f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bikes, Community, cycling, law, tax',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7ae3e5ed-2296-43f6-9d7d-60ee386e01da',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, Lounge room, mobile phone, repair, waste reduction, wet',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7b08225a-a877-413e-ab20-2e8191414ccd',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, Garden, Garden, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7b484804-1380-477a-b47d-7a30fd06df71',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'carbon footprint, Community, Utilities',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7bff163e-c5db-47df-98e3-e7ebc8d22f94',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'birthday, celebrations, Christmas, cooking, edible gifts, Kitchen, recipes, Spare room, vegan, vegetarian',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7c132e88-1613-43c3-9295-547ce7ded06e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'chocolate, Community, cooking, Easter, ethical, holiday, hot cross buns, Kitchen, rabbits, recipes, sustainable',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7c176929-8083-46a4-af6f-a9ae604b588c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'food, food waste, Kitchen, leftovers, reduce food waste, Reducing food waste, save money, Waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7c7ddf2d-ea8e-453c-9c8d-644260f147d0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Food & Waste, Lifestyle',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7cc0f496-5fab-440a-bc7c-911b00114560',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'children, diy, recycled craft',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7cf23177-d485-4dd3-89ea-bc58deeda60d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bayside, highett, workshops',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7f06119a-1f9c-4a29-872a-d069b4107387',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Art, Garden, Garden, moss, the rented spade, walls',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7f2997d6-4e2c-423f-a249-3c19d4ea73f7',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'autumn, Bedroom, cold, Draught Proofing, Energy saving, How to save energy, keep warm, save energy, Spare room, winter',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7f29b659-9221-4dc5-a60b-39399b0791ed',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'co housing, co-operatives, Community, home sweet home, house sharing, Renting',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7f36ba7a-1e1f-4132-b5be-99fbe11d1397',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, cure, Hangover, Kitchen, recipe',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7fbf2885-b531-4fdf-8b1d-c3246cee4ab9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, food, food gardening, Garden, Garden, gardening, Kitchen, vegetables',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '80eaa9be-a165-4362-a221-400613d47a06',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, guide, Melbourne, november, planting, Victoria',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '810c0168-99ee-4003-af1d-ee5d5b54937c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Cheap & Healthy recipes, cooking, Garden, gardening, Kitchen, recipes',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '812f3052-ea4a-4749-b923-10046b76f035',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'free, Garden, Garden, silverbeet, vegetables',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8158f00b-b5a7-46a8-897b-cc93bdbdb2fa',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'assessments, Bathroom, Bedroom, city of Melbourne, city of yarra, energy saver, funding, Kitchen, Laundry, News, state government',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '822c55c7-d901-4f62-bdc8-5e43c804cff9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, gardening, SGA, Sustainable Gardeners Alliance',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '828e6fd0-e5cc-4354-a578-9113a484b952',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, Garden, lawn mowers, wallabies',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '82c6b0be-9b45-4283-8e8a-c26ecaba9a29',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'competition, free, giveaway, magazine, money, wired',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '83091325-4379-4c52-9817-d9e21d4ecbae',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => '30 day vegan challenge, Kitchen, vegan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '838f65b8-eb8f-4273-8f82-1824dd46e8b2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Waste, water',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '843af90a-1dd8-4511-8dd3-d5ff83533ab6',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, electricity, Energy saving, energy saving, Laundry, power monitor, Spare room, Wholesale',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '84b8a8b5-c483-41bc-ba96-16804127827e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cheap, Christmas, cooking, frugal living, Kitchen, recipes, shortbread',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8548671f-1246-4c77-ad79-4c4e8e83145f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'air plants, container gardening, Garden, Garden, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '85605574-f301-4a08-b1a9-8023ed89df83',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Bedroom, green loan, green return, Kitchen, Laundry, sustainability assessment, Utilities',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '862da2e1-1c01-4188-9418-026122c2515d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, Garden, gardening, Gardening in small spaces, Green, pot plants, weekly container gardening spotlight',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8631fcb1-d26b-4679-aa50-2018c39a511f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => '365 ways to go green, Garden, green renting, Kitchen, Mike Lieberman, new york, simply raw recipies, urban gardening',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '865b3c6c-fa17-4cd9-a4e5-39f02e7afd57',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'beer, bottles, Kitchen, moorland, News, plastic, recycling, soft drinks, waste management, waste reduction, ways to reduce waste, week without waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '86724266-f292-438b-9d7a-90dc581cf1dd',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'building, building and home improvement expo, competition, diy, expo, giveaway, home, improvement, Melbourne, News',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '868dda76-388a-41f6-904d-f2d64a93eb34',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, Garden, moving, relocating, renter gardening, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '86cc1f49-7430-4532-a465-e1e0a8a7bb04',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'competition, rental',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '87826c92-b076-4e0b-bb0e-92a8f91cc433',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'consume less, continuos ink system, ink, ink cartridges, office, printing, recycling, Spare room',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8832d76e-0506-417a-8626-9cca883de30c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'carbusters, cars, Community, magazine, Transport, world carfree network',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '88ede51f-acd6-46e7-b622-9222fbf35f8e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'diy, fence, Garden',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8a318498-9d4d-486d-8542-8f39ef56b231',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'babies, Bedroom, children, cleaning, food, Kitchen, Laundry, nappies, Spare room, water',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8a47b4d4-badb-4416-bd81-406c0a006b85',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, coffee, coffee grounds, container gardening, Garden, gardening, greenopolis, Kitchen, mike liebeman, plants, toilets',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8a6363e8-969e-4001-b7ad-c752c73d6620',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Kitchen, Laundry, natural, natural cleaning',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8c43b0c4-4bd1-48fc-a117-1fd20274deb4',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'animals, cooking, ethical, frugal living, Garden, Kitchen, seasonal vegetables',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8c4e031b-5e11-4fd0-b934-2776c2098b53',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, Garden, the rented spade, water, winter',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8c58d40e-7d5c-4bf2-a8dc-4a2421297896',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bokashi, compost, Garden, Garden, Kitchen, renter gardening, scraps, Waste, worms',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8c8ddbfb-ab01-4257-9fb0-94329df4ead6',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bicycles, cate lawrence, craft, cycling, polka dot rabbit, recycled craft, Spare room',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8d55c22a-51a2-4888-9342-a3f673847d4d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'alternative technology association, ata, Bathroom, Bedroom, federal government, Kitchen, Laundry, Low Emission Assistance Plan for Renters, News, renew magazine, Spare room, Utilities',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8e2a79aa-1638-43ec-8332-f9f8d71f073d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Body & Home, business, corporate, Food & Waste, fun, Gardening, Home Sustainability, Lifestyle, team building, training',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8ebc8020-961c-4d0d-8adb-a45bb3777599',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'birds, Garden, Garden, the rented spade, zen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8ef388ba-ee15-4c0b-801a-c191785c4f82',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, Energy saving, energy saving, handmade, local',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8fb26371-5738-4ff2-8b8d-38a56475713f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, decorating, diy, recycling paint, Spare room, wall paper',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8fba1371-cf08-4b31-9592-1b42820144c9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'android, apps, Green, iphone, News',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8fbcc1f3-d53f-487c-9629-121df954ca2e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Paid ads',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9066a2aa-bdd8-4327-98ff-8a7ea0c96ee8',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, Garden, peas, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9111ed76-398b-4886-8b7d-b12efb62b7ff',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'climate change, community power, communitydevelopment, election, Environment, Events, protest, rally',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9157bc5c-b661-4590-8741-093847b9e8a3',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'drought, Garden, Garden, gardening, News',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '917f9389-4c40-488e-a7d4-ac11dc6f8325',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Australia, Bathroom, Events, Melbourne',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '922352b4-73e4-4cd9-9eaf-7d57adc4b93e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Australia, Community, diy, Environment, free, frugal living',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9243b692-abf1-4909-92e4-d227a4eb6a99',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Bedroom, electriticity, frugal living, Kitchen, Laundry, nappies, save energy. dryer, save money, Utilities, Utilities',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9290ed1f-a8ce-4472-85a8-7ec24b2cc648',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Brunswick, city, container gardening, food, Garden, gardening, homegarden, produce, seeds',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '937d666b-fc52-4d67-a6e0-c37eb6d1ddcf',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bush fire, catering, charity, Community, social enterprise, wine',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '93c50021-8c8e-499f-bbb3-9740960ac9fb',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'book review, climate change, Community, csiro, donna green, liz minchin, screw light bulbs, the age, travel',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '93ca459f-23a5-438b-a003-5dc3aa89ce08',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'badges, embroidery, recycled, upcycled, Upcycled gifts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '93d2ba0d-a0f5-403e-9d67-e60befc51843',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, Garden, pots, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '94155f83-9327-4c4d-a24b-23b319f5777a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cinema, Community, movie, oceans',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '94e43d00-dd79-4044-bcd5-784cd1fca9b2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'design',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '95f8588f-51c2-472b-94a3-a38d13c8ebc8',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'balcony gardening, container gardening, Garden, Garden, Water saving, water saving, wicking',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '96244a5a-9539-4a93-b8f8-afe3f50b1fda',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'birds, diy, Garden, Garden, scare',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '976c0869-dd42-4154-9b0a-0dd0439f172a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, free, showerhead, Utilities, water, water saving, water waste reduction',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '977d4c61-baf3-41c1-a094-745497f8a415',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Green, greenscroll, internet, offset, power, routing, Spare room, Utilities, web',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '980181ee-f0a4-43be-9825-a5c7e3072a56',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, gardening, Melbourne, neighbourhood, permablitz',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '981fe545-ecde-41ff-99fc-f82eecf02631',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'aqua wash, japan, Laundry, motta, Utilities, washing, washing powder',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '98704c08-4caf-46e2-a70c-fc5eca7c47ed',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, Garden, rutherglen country houses, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '98841d7c-82f1-4b6f-927f-148bbb2b5df2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'marriage, update, wedding',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '989c5238-b04c-44ee-b905-5a7cd4ab9cf6',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Bedroom, green loans, home improvements, Kitchen, Laundry, News, Spare room, sustainability assessments',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '98bb6dca-7a4c-4283-ac3b-c7b04bec8a0c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, Garden, no dig garden, no dig gardening, renter gardening, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '996751c4-054d-4d26-9cf4-fba628013f6d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'carrots, container gardening, Garden, Garden, potting, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9a63c526-815d-446a-aed4-5d29a7653041',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'food, Garden, Kitchen, recipes, vegan, vegan easy challenge',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9ad02f16-24ef-4e01-84eb-1d9fe11443de',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cohousing, communal living, Community, home sweet home, house sitting, housing, share housing',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9b5414d6-f50e-4094-b573-0077d5cc8ba9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, Garden, gardening, reliable, renter gardening',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9b73e0bc-a9a5-4888-8184-eb8e96a21cd3',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Art, books, Community, consume less, consumption, Lounge room, Spare room, spending',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9bb4098f-3419-4dc9-adef-07073685ee80',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'free, Green, renters, sydney, workshops',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9bbd14fd-68fa-41b7-a56b-25dbee857585',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bread, Kitchen, recipe',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9c1b6859-8aef-4635-93be-138043ab8f06',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'balcony, container gardening, Garden, vegetables, weekly container gardening spotlight',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9cc93c85-b228-4546-b144-d2159720d59c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, craft, rain, recycle, repair, retro, umbrella, vintage, weather',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9d53ec24-6ec7-4a6b-86eb-36c3466357ef',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Logistics',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9e106609-56ca-48c6-9945-837bf5074ef4',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, current cost, elecricity, energy saving, envi, monitoring, Spare room, Utilities',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9edb4bf5-d273-4224-812a-7d3d77a47317',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'carbon footprint, Christmas, Community, consume less, Environment, free, frugal living, Green, recycling, Reuse, seasonal vegetables, spend, travel, waste reduction, ways to reduce waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9fb16c8f-843f-487c-820e-08b5394f8aea',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bean, Kitchen, recipe, vegan, vegetarian',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9fcdf65b-33dc-45c7-9212-d9dbfca0f953',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'diy, DIY. green kitchen, Kitchen, Laundry, Spare room, tutorial',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a15ed06b-dacf-466e-a707-be1c6cd6113d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, Garden, the rented spade, upcycling',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a1ea4b08-0c28-4ffe-b46a-0c755e0c34d8',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Events, Renting, speed renting',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a20f7a40-248a-4e36-83b8-eb185e1b6e26',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cities, city, Green, News',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a23fddf7-56e1-4c8c-968e-1ddef054f8f1',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Bedroom, efficient, Kitchen, living, small, space, Spare room',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a2556285-3f05-43f2-9647-35d46e5db750',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'community, donate, membership, rental sweet rental, support',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a2bb1487-4b6d-4511-b076-3afdf852cf72',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, Garden, Garden, gardening, renter gardening',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a2c179ce-f64a-4c3a-90f1-bec9b07fca0c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'composting, Garden, Kitchen, Laundry, recycling, waste reduction',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a307cb59-dc55-4eb0-ba13-28620e86c49e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'appeal, donate, green renters, rent, support',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a3d0b75e-e89d-4b52-aba6-2ef25a3f5b2f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, cloth pads, craft, News, periods, women',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a4273453-1a0f-444f-8814-4dd0b427c614',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'borage, cocktails, Garden, Garden, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a4aa3247-4e0c-4bd2-a0d5-88ced069bc08',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, cloth pads, Events, goods 4 girls, pad making, periods, Spare room',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a4de6508-4263-4d59-83dd-5bd151651bb2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cling film, food, Kitchen, packaging, sustainlane',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a4e28f7a-2a1f-4ae1-95fa-8bd4bd5b086d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, Garden, Garden, multi culturalism, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a613963a-4f56-4342-9ec7-a8700c30aa79',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'environment victoria, free, green renting, guide, News',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a625027f-f1e2-438d-b502-01e6cef5cb03',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'fence, Garden, Garden, mattress, the rented spade, upcycling, vertical gardening',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a77f9346-1d44-4b8f-89f7-077122df92b0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bath, bristol, cities, Community, sustainability, uk',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a893a2b1-3f79-4e1a-8208-0a6ef11c399d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'advice, festival, sydney rd',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a895c3e5-f862-4804-8868-746f19c3cd30',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bestgreentweet, carnival of the tweets, competition, News, twitter',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a8f19e6d-843d-402e-b940-172f25ace283',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'about us, governance, green renters, News',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a9f3eef7-67fc-4378-8a54-7f9da85054ab',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, electricity, gadget, get involved, home, How to save energy, monitor, tweet, tweet-a-watt',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'aa0a18c0-aa84-439f-984b-ba1870a62364',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, cleaning, Kitchen, Laundry, mcguyver, tips',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ab2d8244-ac7c-4c80-ab4d-426667b2fad5',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'discount, e2, efergy, electricity, electricity monitor, News, Products, special offer, Utilities',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ab3685f9-8f00-4997-8f93-771304d7ba3d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'broccoli, cooking, Garden, Garden, gardening, Kitchen, recipes, seasonal vegetables',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ac076707-c0bd-4e4e-8e37-2aa2a1ebb7b8',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, heat, sewing, sleeping bag, Spare room, warmth',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ac7634ac-dfbd-4997-8b0d-7f0dc77eb42c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, Garden, Garden, herbs, the rented spade, winter',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ac850e78-a74d-4bc1-b04d-a3136c620512',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, electricity, energy saving, how to save electricity, power, Spare room, standby power',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ad0d7642-5b3d-484e-b423-f84b69d51ad0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Bedroom, cleaning, Kitchen, Laundry, natural cleaning, odours, stains',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ad729c15-ea7a-4533-8164-94fe842a7fa7',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, energy saving, Lounge room, portable solar, Renting, solar, Spare room',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ad834c87-4366-46e1-83e3-57b2c090685f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, electricity, energy, How to save energy, power, power saving, Spare room, standby power',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ad98bbc2-b1ab-461b-aa11-ad879e82dd2f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'coffee, Community, cup, get involved, Kitchen, map, reusable',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ad9b03dd-af0c-456b-9293-de149761608d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, green renters, survey, technical',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'af5e1681-1e67-47aa-ba26-7c6e3d550bda',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Kitchen, vegan easy challenge',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b145f849-ba25-41be-b89e-60db2d7deeb6',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'food, freezing, Kitchen, reduce food waste, Reducing food waste, reducing food waste, save money, Waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b23cff30-f0ff-4387-9c73-288aac366240',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'berlin, cities, Community, germany, overseas, sustainability, travel',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b2551046-9c5d-4944-a20a-81698b104774',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'insulation, origin, rebate',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b257d011-cfaa-41f2-b4c2-59e79e3685c0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, How to save water, hughie, Kitchen, Laundry, plants, recycling, save energy, saving, sink, water, water saving',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b268efb4-ded6-4323-8795-cdc6ee152ba2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Cheap & Healthy recipes, chutney, cook, cooking, Garden, Kitchen, preserves, recipe, Reducing food waste, tomato',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b286e675-a9d5-4311-87c7-0f6cb7669dbf',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Christmas, craft, festive, recycling, Reuse, waste reduction',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b35aeb86-1b1e-4a42-af19-a8adf05e67eb',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'hard waste, rubbish, Waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b38cfef2-ce59-4a6f-91e0-110347c082b9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'activities, Brunswick, Community, games, summer, sustainable living festival, upcycling',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b3bfa382-98ef-44e0-aab5-9ded9cddaee2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'competition, recycling, Reuse, television',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b3f64e1a-103b-41de-85b3-954295c47296',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, fundraising, green renters, marketing, office, staff, work',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b3fd6b86-4400-4437-90f4-ad49c845eac7',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Bedroom, federal government, insulation, Kitchen, Laundry, rebate, Spare room, special, Utilities',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b420082b-69a4-42c7-b078-4961e1856081',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'food, local, queen victoria markets, seasonal, shopping',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b4b455c5-e72a-4a20-85d7-ff7e231e0dc0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, carbon footprint, ecoaccountant, energy consumption, Kitchen, Laundry, News, Utilities',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b5409509-990b-464a-ba17-4b2776bc46f5',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cooking, cordial, drinks, food waste, Kitchen, leftovers, lemons, recipes',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b55dac16-2de3-4b48-97af-491923e1f8d5',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Christmas, Community, Easter, holiday, overseas, summer, Transport, travels, winter',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b5d5a32c-9ad3-4dc5-b795-16aca5d1a1c1',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Events, recycle, recycling, Reuse, waste reduction, water',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b7878a21-7bac-431b-9fef-27066a5af3b6',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Australia, Brunswick, ceres, Environment, event, green renters, Melbourne, melbourne social forum, News, promotion, stall, world social forum',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b7b63132-aa85-44dc-ad51-407ed33a65f7',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, goat, hire',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b830b81d-de0f-46fa-8749-84509e42f47b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'assessors, Bathroom, Bedroom, green project, installers, Kitchen, Laundry, lightbulbs, showerheads',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b9384083-9192-446a-9e25-5af9680324f9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'carbon offset, Mobile, phone, Spare room, Utilities',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b9bdc137-f708-4dd6-910e-5b03182fec65',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'affordable housing, Australia, campaigns, environment victoria, moreland energy foundation, one million homes alliance, retrofitting, Victoria',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b9fb4bfa-48c1-4295-b070-b086e361bd90',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'home, home office, lifehacker, office, paper, paperless, Spare room, tree',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b9ff126d-b4eb-42bb-9349-50e73ea95806',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'carrots, Garden, Garden, olympics, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ba030f4e-2951-4845-a9d9-7a317418bf4e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'campaign, carbon footprint, efficient energy use, Environment, Events, footprint, Green, News',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ba82721f-dbf6-4263-9f82-187fbdc5fb7a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, craft, frugal living, Garden, Garden, gardening, Kitchen, Melbourne, pot plants, seasonal vegetables, waste reduction',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bb0c9dd9-229b-4612-9177-df5cf7a22b9b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'food, food waste, Kitchen, reduce food waste, Reducing food waste, save money, Waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bc3d5281-ffe7-41fa-b5f3-65fd63bfc07d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'craft, moreland, plastic, polka dot rabbit, recycling, Spare room, waste reduction, week without waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bc678f27-d157-4e6b-a0b9-f4d88212456b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'electricity, energy consumption, gas, smart meter, water, water saving',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bc8f8727-7be7-48d1-8a8b-75ac9635f2b1',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'costume, halloween, humour, party',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bcd7002b-69f7-4da3-a567-6b654bb519ee',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, Garden, melbourne university, smart water, Utilities, water',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bcf70826-2382-49eb-b926-7eabf47dbe8e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'community, event, Garden, Kitchen, market',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bcf77094-d139-4eb5-a655-4f8470aa0d91',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'balcony, flickr, Garden, Garden, Green, trestle',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bd66850e-2cb9-4d36-bcd2-d7f828d9e121',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bottle, ecotanka, water',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bdbb05bb-43d7-47b0-be2e-7ecf331569d2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Lower left',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'be916d8f-bec3-40e9-b8ba-510f12376ed2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, Christmas, diy, festive, Lounge room, recycle, Spare room, upcycle',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bfd4f970-c637-4793-a64a-a924c880fc27',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bush fire, Garden, help, News, seedlings',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bfdd2f83-70cb-4e41-9b1a-54b5dbadb6fb',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Kitchen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c09a93a1-f0dc-48a9-8b78-681eda7cbdf2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'animals, Australia, birds, bushfires, charity, Environment, fundraising, Melbourne, News, Victoria',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c14118e5-3d91-4409-8e5d-2eaf9ebdba64',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'animals, birds, bushfires, charity, Environment, fundraising, Melbourne, News, Victoria',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c3f4fc44-fede-4090-976e-7dc4e5bcaa15',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'borax, consume less, Environment, home made washing powder, Laundry, vegetables, washing, water, water saving',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c44851a0-99bd-4def-8b53-9405c3958977',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, Garden, Garden, lettuice, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c472fe96-df5d-4651-8568-f0cc47f45ac8',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, carbon footprint, cooking, craft, diy, door snake, draught proofing, food, insulation, keep warm, Kitchen, Laundry, save energy, Spare room, waste reduction, winter, winter vegetables',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c5955023-0345-4697-a15e-09c8417a195c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'draught proofing, Environment, heater, heating, keeping warm in winter, warm, winter',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c5d48bf3-d8a9-457f-a681-74ecbe8ddf87',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'balcony gardening, Community, container gardening, Garden, Indira Naidoo',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c6023ce9-1b71-405f-996f-027634a809bb',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bread, Cheap & Healthy recipes, cooking, food, food waste, Kitchen, recipes',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c62b4333-ee67-404f-9a42-beb6998f0ad3',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Christmas, cooking, recycle, recycling, Spare room, Waste, waste reduction',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c6535dcc-5063-4187-a09f-15bbc714ca58',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'News, website',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c679e1c0-a814-47f7-8593-8dcc9ef457fa',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, housing crisis, Renting',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c6d37d75-3e9f-4229-bc30-bebab98fa909',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'competition, container, food, Kitchen, re-use, storage',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c6d6481e-eada-4fd7-8467-c400257501ca',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Christmas, gift, Kitchen, Merchandise',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c72f13de-6f08-420e-b226-8daba2d36897',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'carbon footprint, electricity, energy efficiency, Kitchen, Laundry, light bulbs, recycle, recycling, Spare room, Utilities',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c7675e5a-80f4-4769-b643-2db5c3b27d58',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, energy efficiency, freiburg, germany, overseas, travels',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c7a4f705-bf25-4c9c-8caa-896675961d65',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'composting, Garden, Garden, gardening, Worm Farm',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c8a04f93-d55d-4e32-8470-d2582c2ad91e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, Garden, Garden, polystyrene, small space gardening, the rented spade, upcycling',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c90b524b-4132-4a0e-b148-9d699cd1b310',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Christmas, craft, diy, presents, Spare room',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c90f6206-7d56-4045-8fce-faeaf36d765e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Kitchen, Kitchen, portable',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c964786a-7e4f-4e39-b92a-ef59624f9b36',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Bedroom, Community, energy, energy saving, how to, How to save energy, Kitchen, Lounge room, save money, tips, Tutorials',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ca1d0aaa-e8e8-4987-bc3b-28cc76bf2556',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'diet, Garden, Kitchen, vegan, vegan easy challenge',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ca252dd0-b2c4-4fab-84bb-468365781b7b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bath products, Community, diy, make your own, natural, skin care',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cb1e920a-cf7b-4420-a34e-9fd48d264b86',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'celebrations, Christmas, Community, festive season, Kitchen, Spare room',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cb2c3a80-4a74-43fa-9f24-b4e88b94c33e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'consumption, electricity, monitoring, origin, power, saving energy, Utilities',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cb60b19b-619d-4910-b8ff-545390bdf654',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'eco house, Environment, television',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ccdd60e6-bce2-466b-ad7e-11bbecb09ba5',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'kids, monkey, recycled, toy, upcycled, Upcycled gifts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cd30deca-cdc0-4731-8ebd-8c4c54db46bc',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Australia, challenges, Environment, enviroweek, Green, News',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cd76dd9a-209a-459c-a6b7-65958c8df146',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cooking, Environment, Kitchen, waste reduction, ways to reduce waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cdd1f46b-d6d3-4dcb-a23f-7f0515c93e99',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'food, Kitchen, leftovers, reduce food waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ce0ccbc0-11f0-4277-b793-9707dd47804a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'charity, Community, film night, fundraising, get involved, not for profit',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cf04013a-bbfe-4e24-bc5d-4ef3e9b9dc44',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'free, fruit and vegetables, Garden, gardening, Kitchen, News, workshop',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cf2be626-31c0-41ed-87b8-6715f29c43d7',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bottled water, tap water, Utilities, water, we want tap',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cf954f79-6b36-4608-8bbc-4830633c8585',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'asia, ewaste, gadgets, gizmos, recycle, Spare room, Waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cfe00f98-210f-45ce-b46d-6c54337cdb74',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'brighton, coast, Community, england, greens, travel, uk',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd05048ac-d8f1-450f-87ee-fbf97d581253',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, diy, Garden, Reuse, seasonal, vegetables, weekly container gardening spotlight',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd094c783-6bff-4a74-9e9a-bcc182737a3a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Events, green renters, News, slf, sustainable living festival, sydney, thoughts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd17eba08-26f8-4a42-8f57-6d942f96274a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cold, hanky, Merchandise, merchandise, sick',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd230e32c-6802-4b64-90af-fc5e000a3729',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, Energy saving, energy saving, hot water bottle, How to save energy, keeping warm in winter, winter',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd259ca5d-12aa-4a20-b46f-32fa2e15c069',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Bedroom, diy, green painters, green painting, Kitchen, Laundry, paint, painting, Spare room',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd2fd2a6b-63e6-47d5-a81f-593b75b7cf52',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'documents, get involved, processes, volunteer, volunteering',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd337ed71-f6f8-4bec-b658-263ef0acb861',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Brunswick, Community, community gardens, Garden, gardening, guerrilla, moreland',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd3603f3e-72a0-42b3-a5ac-824f6a1733ec',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, games, green games, projects',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd3a4f180-6c8e-4c8b-8d8e-0a51b3067491',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Australia, ethical, Events, food, gardening',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd44b64ae-7a15-4cfd-b962-7c354afc2bba',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Australia, carbon footprint, food, moreland, recycle, recycling, Reuse, waste reduction, ways to reduce waste, week without waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd4f1c63d-3b62-4c01-b908-4fb9e41ad48b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'craft, diy, recycling, repairs',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd532019a-6a3f-4695-b1d9-549c9fe0c887',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'ads, green renters, housing, landlords, News, tenants',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd57554f6-37aa-455b-a48d-bd03d0cca049',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, Garden, gardening, spring, vegetables',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd6788d2e-32c1-4043-98a2-6e37d6132712',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, Garden, gardening, recycle, tutorial, weekly container gardening spotlight',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd7a2f716-c8b6-48fb-81f4-54fdf29b4c24',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'backyards, Garden, gardens, landlords, plants, vegetables',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd825c0e4-43ef-4887-8b77-46a7ae2aeef9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, current affairs, politics, world',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd8b8f6c3-8da0-4c09-b52e-547445fb25e0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Garden, How to save water, Kitchen, Laundry, renter gardening, water, water saving',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd9374e9a-e107-4811-ad88-68662caaacd2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Cheap & Healthy recipes, dressing, Garden, harissa, Kitchen, labne, mint oil, pesto, Reducing food waste, sauce, tahini',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd9bffade-032a-42dc-895f-a6b8af1d7320',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'dumpster diving, ethical, freeganism, Kitchen, shopping',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd9d02744-7335-42ce-92c2-031364b88ef8',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Chickens, Garden, Garden, the rented spade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'da17dfc4-539b-4b46-a154-8efcf810f4cf',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, electricity, How to save energy, LED, lighting, lights, save energy, Spare room',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'da4ea5c7-ecb9-496f-8b9b-ac49686f83b1',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'ink, slashdot, soy, Spare room',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dacf9e9a-8f69-4cdd-a906-47a6e580e80b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'growth, image, News, recession, the age',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dadc9937-b015-4c22-9c86-216a65551662',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'advice, Art',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dbbd62c5-ba76-4d91-94de-249aa1240e5b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'animals, birds, News, water',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dc781137-f50c-4cbc-aa18-1984ce8e5259',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Energy Waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dcd4cdfb-1af3-4417-a3ee-67b68652b46c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Garden, grey water, Kitchen, Laundry, save energy, water, water saving',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dd13deb7-849b-4eba-a3b6-7873e9807042',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, community, volunteer',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'de586c3a-8c92-419f-ac5e-21f879d7122f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'diet, food, Kitchen, vegan, vegan easy challenge',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'de9e539a-c0f5-48d6-b082-d4af46cb7991',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, Gardening in small spaces, repurpose, tire, upcycling, Waste, waste management',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'df9db3da-8461-4608-bf8a-74cb8ccc059c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'dolls, Garden, Garden, gardening, props, the rented spade, upcycling',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dfc90716-5317-45b2-a44d-46e2bd7a0a9c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'cooking, food, Garden, Kitchen, preserves, preserving, reduce food waste, Reducing food waste, save money, Waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e0393b23-b2a3-41af-880f-9a901bdee1a8',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'food, food gardening, Garden, gardening, News',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e053ebda-69b0-424a-bc3d-fb237c9603aa',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'genetically modified ingredients, greenpeace, Kitchen, News, truefood',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e09f94f5-ceaa-4129-a5be-293f7c10ef09',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'chocolate',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e0ec063c-b462-4b5c-b56f-1f707ebdd5ab',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'enviroweek, event',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e102b968-8463-4bfd-8f63-2f5ed24a39d9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Food & Waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e158e0fb-842d-475b-a05c-e5e3466fe299',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Air Conditioning, Bedroom, cool, Spare room, survive, Utilities, Video',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e1992fec-8310-4ff2-9b29-2b64b7359f0d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Christmas, decorating, diy, food, fruit and vegetables, Garden, Garden, gardening, Kitchen, Reuse, seasonal vegetables, vegetables',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e1c52d07-eedd-45e1-a836-8be19767f85a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, donation, funding, games, green games',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e1d15071-401d-4daf-89ad-706258424d11',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Community, dating, Green, Kitchen, love, relationships',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e2284d40-5516-44e0-a8b4-c8cbb54b3006',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'carbon footprint, coffee, keep cup, keepcup, Kitchen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e246407d-7089-43c9-9e99-40785ecd04b7',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden, gardening, guerilla, renter gardening',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e2504503-1d17-4b23-9f32-397d19e223fe',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'animals, Australia, ethical, free, Kitchen, News',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e287a529-ec52-467c-bac3-561369cbc64b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Bedroom, insulation, Kitchen, Laundry, Low Emission Assistance Plan for Renters, News, News, rebate, renters, Spare room, Utilities',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e379f9bd-8709-4885-86b1-32db4fc15427',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bristol, cafe, courses, Environment, folk, food, house, News',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e384ed5c-077a-4478-a794-6ffdf614caf0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, diy, landlords, Lounge room, painting',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e43c0080-f5ec-476b-bb97-733ebdb16d45',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, Bedroom, Garden, green collect, Kitchen, Laundry, recycling, Waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e466e7d7-3b1f-441b-8c87-6a12e6b277e7',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'composting, Garden, wast reduction, Worm Farm',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e49bcd61-b1fe-45eb-b4a3-97b4d718cf74',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Australia, Bathroom, Bathroom, Bedroom, buckets, diy, Garden, Kitchen, Laundry, Melbourne, napkins, Renting, Spare room, Tutorials, washing',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e527a6d7-fc58-476a-80ef-d9ed677deb49',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'carbon footprint, consumer power, ethical, food, Kitchen, News',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e665c25f-572f-4f73-af5c-b0a1c25b34e7',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'efficiency, exchange, lightglobes, showeheads, Spare room',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e772d984-c96e-4e9a-8b75-926b933a458e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, flush, grew water, How to save water, save water, toilet, Waste, water',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e7d36227-a8d0-4e6b-a6a8-ecf1f51f8beb',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Environment, food',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e82c3758-d76a-4e70-8037-6c0a72be2b3e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Garden',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e90fd56c-c492-4d02-9fac-54eb6a715251',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'food, Kitchen, leftovers, meal, Reuse, Waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e9e6639b-48de-42d3-a306-576e6c3a8d08',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, boilers, energy, heating, How to save energy, keep warm, Kitchen, Products, save energy, water',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'eaf3ba3c-f69d-422d-9e7d-1f4e7a3e903d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, consume less, garage, garage, garage sale, Kitchen, second hand',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'eb3d51db-8600-46e3-bb0b-6992bf6e7c98',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'gadget, recycle, Reuse, Spare room, upgrade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'eb9ed119-983f-47ac-99ef-efef1df223dd',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, electricity, How to save energy, Kitchen, Lounge room, Power monitoring, smart meters, Watts Clever',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ec55e25c-8a56-48d8-bac7-df391d7e807a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'competition, earthsharing victoria, Environment, film, housing, News',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'edc1ab27-4f13-4bc0-ba35-23c4abb557a2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, freecycle, giving, iphone, recycle, Spare room, yoink',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ee570baa-5c19-46ec-8d1a-3f321e7d6270',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'about, Community, jobs, work',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'efe4db88-44de-4575-9a9b-4852f90d3f96',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'advertising, ber, green beer, green washing, Kitchen, media',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f07382f0-46aa-4d0f-8d72-e5cf779e894e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, Bedroom, recycle, Reuse',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f07737b9-748c-40ec-b213-6950edb187a6',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, Community, donate, Garden, Kitchen, Laundry, Spare room, support',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f0850dd6-c931-4f75-8f27-b7cc91323af0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'august, goals',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f188e65c-059c-483c-8919-5071cbc7f692',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, Drafts, energy, How to save energy, insulation, Laundry, Windows',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f2b41060-a262-4487-a577-584cc337b1e2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'food, food waste, Kitchen, reduce food waste, Reducing food waste, save money, stock, stock pots, Waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f2bd1976-fa05-4651-bf67-90c66d19f4c0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, budget, clothing, collaborative consumption, consume less, second hand, vintage',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f30ef845-8a4a-48f7-b7bb-e2d9bbe7fd27',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, free, frugal living, Garden, Reuse',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f35e2066-36a6-46b8-b261-a13eeeaf6eca',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'electricity, energy saving, green energy, Utilities, water',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f3e53d45-4fd9-4329-af63-b8dce54fccc3',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, gift, Lounge room, present, recycled, repurposed, Tintin, Upcycled gifts, wallet, Wholesale',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f4f0b801-228d-4e9e-abfe-882dded1179e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'book, food, green food generation, hayden wood, Kitchen, sustainability',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f5112042-055f-4c48-adf6-dbc1810b69be',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'campaign, carbon footprint, efficient energy use, electricity, footprint, green renting, News, Renting',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f548c943-ba6a-4367-968f-289ff72d7816',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'get involved, green renters, News, stalls, volunteer, workshops',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f5ad0a30-4683-415e-abab-1f3afe8079d6',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Community, greenwash, sins',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f5d8d06d-d358-4b69-b243-7b65a604f26b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Christmas, festive, gifts, Spare room, Upcycled gifts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f65dfd9c-56f9-478b-b231-655fb423558b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'funny, Garden, humour, milk crate man, reusing milk crates',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f67493a5-71f5-407f-b329-ade3023307b8',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bananas, cooking, Kitchen, muffins, recipes',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f6b7a3d0-f92e-4d92-ac0a-c2f20a5dfa7b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Events, Kitchen, News, News',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f771b98d-c384-4fa1-8a3c-0e3fe343d80c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'diggers, Garden, gardening, geurilla, seeds',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f89fbac3-a412-4a21-9eca-85b22983e48a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'container gardening, Garden, Garden, herbs, Water saving, window box',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f918b08b-bdc0-4f4c-8d25-f2e01d7c8d8e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'BPA free, Storage, water bottle',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f9b403a3-1bcd-4df5-b1c1-f1753de8e825',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'consume less, cooking, energy, Kitchen, recipes, reduce food waste, Reducing food waste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fa1502ea-4683-432c-8099-acedcbae56d0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'carrotmob, community, food, hawthorn, News',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'faac2ca9-9a53-4f70-9501-021c85a49bcd',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'advice, campaign, carbon footprint, Community, Environment, things we like',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fbedcf98-0062-46db-876e-1642749ff21c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'backyard, container gardening, Garden, indigenous, small space gardening',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fc5e9221-0c12-4dfe-a271-7da1d2c08cbf',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bathroom, energy saving, How to save water, save water, shower, water, Water saving, water saving',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fde508eb-14ba-4c44-8a0e-b33cf10e915e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Bedroom, diy, milk crates, reusing milk crates, Spare room, tutorial',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fe3029e0-218a-4e7c-8bb4-98b79a5c65e6',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'animals, backyards, Chickens, chooks, Garden, keeping chickens, pets',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ff06c7c9-e7d8-4685-88ef-8094bf9cd3d4',
    'vocabulary_machine_name' => 'tags',
  );
  return $terms;
}
